#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Nov 23 09:52:22 2022

@author: tom.earnest
"""

import matplotlib.pyplot as plt
import pandas as pd

predicts1 = pd.read_csv('model1_predicts.csv')
predicts2 = pd.read_csv('model4_predicts.csv')
submits = pd.read_csv('beach_demand_forecast/sales_test.csv')
submits['date'] = pd.to_datetime(submits['date'])

predicts1 = predicts1.merge(submits, on='id')
predicts2 = predicts2.merge(submits, on='id')

item = 3

df1 = predicts1[predicts1['item_id'] == item]
df2 = predicts2[predicts2['item_id'] == item]

fig, ax = plt.subplots()

ax.plot(df1['date'], df1['item_count'], label='model 1')
ax.plot(df2['date'], df2['item_count'], label='model 2')
ax.legend()